version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5
executors:
  circleci_machine:
    docker:
      - image: circleci/node:14.15
    working_directory: ~/repo

commands:
  install_node_dependencies:
    steps:
      - run:
          name: Install Node dependencies
          command: npm ci

  test_lib_transpilation:
    steps:
      - run:
          name: Test lib transpilation
          command: npm run lib

  test_lib_import:
    steps:
      - run:
          name: Test JS library imports
          command: |
            npm run lib-test:setup
            cd tools/test-lib/react-app
            npm run test:ci

  run_eslint:
    steps:
      - run:
          name: Run Eslint
          command: npm run lint

  run_javascript_tests:
    steps:
      - run:
          name: Run JavaScript tests
          command: npm run build:css && npm run test:ci

  run_secret_scan:
    steps:
      - run:
          name: Run secret scan
          command: make secret-scan

  run_security_scan:
    steps:
      - run:
          name: Run security scan
          command: make security-scan

  cleanup:
    steps:
      - run:
          name: Cleanup
          command: make clean

  build_application:
    steps:
      - run:
          name: Build application
          command: npm run build

  deploy_gh_pages:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v${CACHE_VERSION}-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v${CACHE_VERSION}-dependencies-
      - install_node_dependencies
      - build_application
      - add_ssh_keys:
          fingerprints:
            - "9a:fe:61:f4:d6:c2:c1:58:75:c9:72:56:6e:53:fd:8b"
      - run:
          name: Deploy to GitHub Pages
          command: |
            cd build
            git config --global user.email circleci@circleci.com
            git config --global user.name CircleCIBot
            git init
            git checkout -b gh-pages
            git add -A
            git commit -m 'Demo build [ci skip]'
            git remote add origin https://github.com/quantumblacklabs/kedro-viz.git
            git push origin gh-pages --force

  build:
    description: Run build
    steps:
      - checkout
      - restore_cache:
          keys:
            - v${CACHE_VERSION}-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v${CACHE_VERSION}-dependencies-
      - install_node_dependencies
      - test_lib_transpilation
      - test_lib_import
      - run_eslint
      - run_javascript_tests
      - run_secret_scan
      - run_security_scan
      - cleanup
      - save_cache:
          paths:
            - node_modules
          key: v${CACHE_VERSION}-dependencies-{{ checksum "package.json" }}
      - build_application

jobs:
  build:
    executor: circleci_machine
    steps:
      - checkout
      - restore_cache:
          keys:
            - v${CACHE_VERSION}-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v${CACHE_VERSION}-dependencies-
      - install_node_dependencies
      - test_lib_transpilation
      - test_lib_import
      - run_eslint
      - run_javascript_tests
#      - run_secret_scan
#      - run_security_scan
      - cleanup
      - save_cache:
          paths:
            - node_modules
          key: v${CACHE_VERSION}-dependencies-{{ checksum "package.json" }}
  deploy:
    executor: circleci_machine
    steps:
      - checkout
      - setup_remote_docker
      - run:
            name: build docker and publish
            command: |
              ./build_image.sh $CIRCLE_TAG --publish --latest


workflows:
  build_and_deploy:
    jobs:
      - build
        filters:
          tags:
            only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
